data = ["Rajkot", "Surat", "Baroda", "Bhuj", "Jamnagar", "Ahamdabad", "Morbi"]
print(data)
data.insert(3,'jd')
print(data)
data.remove('Surat')
print(data)
del data[5]
print(data)
print(data[-1])
print(data[1:5])
print(data[0:5])
print(data[0:])
print(data[:3])
print(data[:])
print(data[-1])
print(data[-5:-1])